In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4]])

In [3]:
b = np.array([[5, 6], [7, 8]])

In [4]:
# 

a * b

array([[ 5, 12],
       [21, 32]])

In [5]:
a @ b

array([[19, 22],
       [43, 50]])

In [6]:
np.matmul(a, b)

array([[19, 22],
       [43, 50]])