In [1]:
from intervals.number import Interval as I
from intervals.methods import (lo,hi,mid,rad,width,intervalise)
from intervals.random import uniform_endpoints 
from intervals.mat_features import initialise_interval_matrix, create_interval, dot, rowcol, rowcol2, intvl_matmul

In [2]:
import numpy as np

In [3]:
%load_ext autoreload
%autoreload 2

# interval matrix `calculation` test

- test with simple 3 by 3 case
- current workflow will work as long as there is no shape as 2

In [4]:
a = np.arange(9).reshape(3,3)

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# vev @ vec

v1 = create_interval(matrix=a)
v1

[0. 0.] [0.9 1.1] [1.8 2.2]
[2.7 3.3] [3.6 4.4] [4.5 5.5]
[5.4 6.6] [6.3 7.7] [7.2 8.8]

In [7]:
v1.shape

(3, 3)

In [8]:
# create a row vector 

row_vec = v1[0]
row_vec

[0.0,0.0]
[0.9,1.1]
[1.8,2.2]

In [9]:
row_vec.shape

(3,)

In [10]:
# ''' add one more dimension succeeded '''

# added_dim = row_vec[np.newaxis,:]
# print(added_dim.shape)
# added_dim

In [11]:
''' lower dimension failed '''

# np.ravel(added_dim)

' lower dimension failed '

In [12]:
# matrix which is v1
'''
(3, ) @ (3,3)

'''
result = rowcol2(x=row_vec, W=v1)
result

[12.15 18.15] [14.58 21.78] [17.01 25.41]

In [14]:
result.shape

(1, 3)

In [35]:
result_ = intvl_matmul(x=row_vec, W=v1)
result_

[12.15 18.15] [14.58 21.78] [17.01 25.41]

# vector computation

### scaler interval @ vector interval

In [15]:
# scalar
x = 2.

In [16]:
x_intvl = create_interval(matrix=x)
x_intvl

[1.8,2.2]

In [17]:
x_intvl.shape

()

In [18]:
W1 = np.array([[1, 3, 5]])
# W1 = np.array([1, 3, 5])
W1.shape

(1, 3)

In [19]:
W1

array([[1, 3, 5]])

In [20]:
W1_intvl = create_interval(matrix=W1)
W1_intvl

[0.9 1.1] [2.7 3.3] [4.5 5.5]

In [21]:
W1_intvl.shape

(1, 3)

In [22]:
#
''' 
(3, ) @ (1, 3)
'''


h1 = x_intvl * W1_intvl
h1

[1.62 2.42] [4.86 7.26] [ 8.1 12.1]

In [23]:
h1.shape

(1, 3)

In [24]:
# tst= dot(h1, row_vec)

In [25]:
# another test

W2 = np.array([1, 3, 5])[:, np.newaxis]
W2.shape

(3, 1)

In [26]:
W2_intvl = create_interval(matrix=W2)
W2_intvl

[0.9 1.1]
[2.7 3.3]
[4.5 5.5]

In [27]:
W2_intvl.shape

(3, 1)

In [28]:
# to mimic the second layer propagation, from h1 to output 

'''
# (1 by 3) * (3 by 1)
y = hidden_tensor * W2_int
'''

'\n# (1 by 3) * (3 by 1)\ny = hidden_tensor * W2_int\n'

In [30]:
y_hat = intvl_matmul(x=h1, W=W2_intvl)

In [31]:
y_hat

[[51.03 93.17]]

In [33]:
y_hat2 = intvl_matmul(x=h1, W=v1)

In [34]:
y_hat2

[[ 56.862 103.818] [ 69.984 127.776] [ 83.106 151.734]]